### ISSUE TITLE
CRLF to LF tip on react native README on main ricohapi site make pull request

### ISSUE THREAD

**Issue by codetricity** [theta360developers/theta-client-guide#29]
Add short sentence or two on getting the mkproject.sh script to work on Windows 11 using the CRLF to LF conversion technique

Here:
https://github.com/ricohapi/theta-client/pulls

**Comment by AirTechWick** [comment]
Added this section to my Guide now, its complete

**Comment by codetricity** [comment]
The issue to make the pull request on the ricohapi site.

https://github.com/ricohapi/theta-client/pulls

**Comment by AirTechWick** [comment]
I see I`ll try and do that for the main ricohapi

**Comment by codetricity** [comment]
OK.  If possible, sit down with @jcasman and make the pull request.  If you have time, do it today.
