### ISSUE TITLE
update theta-client readme to link to  https://theta360developers.github.io/sdk/

### ISSUE THREAD

**Issue by codetricity** [theta360developers/theta-client-guide#30]
When the theta-client-guide document is improved to state where it is useful to the public, update the theta-client/README.md file with a link to the gate.

https://theta360developers.github.io/sdk/

**Comment by codetricity** [comment]
https://github.com/ricohapi/theta-client/pull/14#issue-1634484690

**Comment by simago** [comment]
I added a description to theta-client/README.md by https://github.com/ricohapi/theta-client/pull/21
