### ISSUE TITLE
Fixing all caps in section text

### ISSUE THREAD

**Issue by jcasman** [theta360developers/theta-client-guide#51]
Please fix RICOH THETA in all caps in the section text on the left side of the docs:

<img width="438" alt="Screen Shot 2023-06-26 at 10 16 33 AM" src="https://github.com/theta360developers/theta-client-guide/assets/1075520/1571477a-a13a-4b85-9b9f-694d7f29cb32">

**Comment by codetricity** [comment]
might be better to use the name of the project on GitHub, which is theta-client

**Comment by AirTechWick** [comment]
👍Okay I'll work on this

**Comment by AirTechWick** [comment]
![image](https://github.com/theta360developers/theta-client-guide/assets/82003999/995532d3-619b-4e3b-a2e5-10a5ee46076a)
Fixed this

**Comment by codetricity** [comment]
@jcasman should you close the issue?

**Comment by jcasman** [comment]
Yes! Closing.
